### ISSUE TITLE
Linking Diagram with Tables by using New-DiagramEvent is currently broken

### ISSUE THREAD

**Issue by h00jraq** [EvotecIT/PSWriteHTML#449] opened 2024-07-31 11:54 UTC
I've tried following the docs and also the below article and none of the examples with using `New-DiagramEvent` work atm. Using Even the simple example from https://evotec.xyz/nested-tabs-diagram-updates-diagram-events-calendar object-and-more-in-pswritehtml/

```
$Processes = Get-Process | Select-Object -First 10
$TableID = 'RandomID'

New-HTML -TitleText 'My Title' -UseCssLinks -UseJavaScriptLinks -FilePath $PSScriptRoot\Example30-LinkedProcesses.html -ShowHTML {
    New-HTMLSection -Invisible {
        New-HTMLPanel {
            New-HTMLTable -DataTable $Processes -DataTableID $TableID
        }
        New-HTMLPanel {
            New-HTMLDiagram -Height '1000px' {
                New-DiagramEvent -ID $TableID -ColumnID 1
                New-DiagramNode -Label 'Processes' -IconBrands delicious
                foreach ($_ in $Processes) {
                    New-DiagramNode -Label $_.ProcessName -Id $_.Id -To 'Processes'
                }
            }
        }
    }
}
```

When you click on the Diagram Node, nothing is highlited/selected in the table.
Tried other examples and they also did not worked.
Dev Console in chrome only shows:
![image](https://github.com/user-attachments/assets/62ac5ea0-2267-4c11-8076-6127c31210ff)

P.S
@PrzemyslawKlys we have talked about this today on LinkedIn. Filip here :)

**Comment by PrzemyslawKlys** [comment] 2024-08-01 06:42
The issue is now fixed. Keep in mind that ColumnID needs to match the order of the column in the table. So if you Id column which are you referencing in New-DiagramNode is first it should be 0, but if notice Get-Process sometimes puts it on 9th location which won't work.

```powershell
$Processes = Get-Process | Select-Object -First 10 -property Id, ProcessName
$TableID = 'RandomID'

New-HTML -TitleText 'My Title' -FilePath $PSScriptRoot\Example30-LinkedProcesses.html {
    New-HTMLSection -Invisible {
        New-HTMLPanel {
            New-HTMLTable -DataTable $Processes -DataTableID $TableID -DataStore JavaScript
        }
        New-HTMLPanel {
            New-HTMLDiagram -Height '1000px' {
                New-DiagramEvent -ID $TableID -ColumnID 0
                New-DiagramNode -Label 'Processes' -IconBrands delicious
                foreach ($_ in $Processes) {
                    New-DiagramNode -Label $_.ProcessName -Id $_.Id -To 'Processes'
                }
            }
        }
    }
} -Online
```

**Closed by PrzemyslawKlys** 2024-08-01 06:43 UTC
Labels: bug
