### ISSUE TITLE
Align column text to the left

### ISSUE THREAD

**Issue by matteu31400** [EvotecIT/PSWriteHTML#226] opened 2021-04-14 14:03 UTC
Hello,

I don't know where to find the good way to align my column text to the right.
I just test your module with these command :

```powershell
function Get-ReportProcess
{
    get-process | foreach {
        [pscustomobject]@{
            Name = $_.ProcessName
            ID = $_.id
        }
    }
}

$ReportProcess=Get-ReportProcess

New-HTML -Name "My title" -FilePath c:\Example04.html  {
    New-HTMLTab -Name "Inventory" {
        New-HTMLSection -name Process{
            New-HTMLTable -DataTable $ReportProcess
        }
    }
}
```

I have Name and ID column in the center and I would like them to be on the left. + don't use all the page for 2 column. I would like to use only the space I need with the table.

Thanks

**Comment by PrzemyslawKlys** [comment] 2021-04-14 15:20
`New-TableHeader` is what you need.

```powershell
function Get-ReportProcess {
    Get-Process | ForEach-Object {
        [pscustomobject]@{
            Name = $_.ProcessName
            ID   = $_.id
        }
    }
}

$ReportProcess = Get-ReportProcess

New-HTML -Name "My title" -FilePath c:\Example04.html {
    New-HTMLTab -Name "Inventory" {
        New-HTMLSection -Name Process {
            New-HTMLTable -DataTable $ReportProcess {
                New-TableHeader -Alignment left -Names 'Name', 'ID'
            }
        }
    }
} -ShowHTML -Online
```

For size, you can play with size of sections. By design PSWriteHTML tries to fit the page of 100% width. 

```powershell
function Get-ReportProcess {
    Get-Process | ForEach-Object {
        [pscustomobject]@{
            Name = $_.ProcessName
            ID   = $_.id
        }
    }
}

$ReportProcess = Get-ReportProcess

New-HTML -Name "My title" -FilePath c:\Example04.html {
    New-HTMLTab -Name "Inventory" {
        New-HTMLSection -Invisible {
            New-HTMLSection -Name Process {
                New-HTMLTable -DataTable $ReportProcess {
                    New-TableHeader -Alignment left -Names 'Name', 'ID'
                }
            } -Width 30%
            New-HTMLSection -Name 'Something else' {

            }
        }
    }
} -ShowHTML -Online
```

![image](https://user-images.githubusercontent.com/15063294/114735655-b29efc00-9d45-11eb-9cfa-e00718c78330.png)

**Comment by matteu31400** [comment] 2021-04-14 17:45
Thank you for this fast answer.
It's better.
Is it normal it's not totally on the left ?
![2021-04-14_19h40_31](https://user-images.githubusercontent.com/55273549/114755187-ab81e900-9d59-11eb-8bcd-bc8397d68a2e.png)

Then, I would like to know if there is some help for each parameter ? Because New-HTMLTable has lot of possible parameter and get-help has no description and on your website I see lot of example but no description on each possibilities.
It's the first time I use it, maybe I don't look at the good place...

Finally, many thanks for this module because I used a little html / css and this module will make my life easier and dynamic search is awesome :). I see there are lot of different module I need to read a little each of them but this one is just excellent.

**Comment by PrzemyslawKlys** [comment] 2021-04-14 17:57
You should read:

- 🔗 [Meet Statusimo – PowerShell generated Status Page](https://evotec.xyz/meet-statusimo-powershell-generated-status-page/)
- 🔗 [Meet Dashimo – PowerShell Generated Dashboard](https://evotec.xyz/meet-dashimo-powershell-generated-dashboard/)
- 🔗 [Dashimo – Easy Table Conditional Formatting and more](https://evotec.xyz/dashimo-easy-table-conditional-formatting-and-more/)
- 🔗 [Out-HtmlView – HTML alternative to Out-GridView](https://evotec.xyz/out-htmlview-html-alternative-to-out-gridview/)
- 🔗 [Meet Emailimo – New way to send pretty emails with PowerShell](https://evotec.xyz/meet-emailimo-new-way-to-send-pretty-emails-with-powershell/)
- 🔗 [All your HTML Tables are belong to us](https://evotec.xyz/all-your-html-tables-are-belong-to-us/)
- 🔗 [Sending HTML emails with PowerShell and zero HTML knowledge required](https://evotec.xyz/sending-html-emails-with-powershell-and-zero-html-knowledge-required/)
- 🔗 [Dashimo (PSWriteHTML) – Charting, Icons and few other changes](https://evotec.xyz/dashimo-pswritehtml-charting-icons-and-few-other-changes/)
- 🔗 [Working with HTML in PowerShell just got better](https://evotec.xyz/working-with-html-in-powershell-just-got-better/)
- 🔗 [Comparing two or more objects visually in PowerShell (cross-platform)](https://evotec.xyz/comparing-two-or-more-objects-visually-in-powershell-cross-platform/)
- 🔗 [Easy way to create diagrams using PowerShell and PSWriteHTML](https://evotec.xyz/easy-way-to-create-diagrams-using-powershell-and-pswritehtml/)
- 🔗 [Nested Tabs, Diagram Updates, Diagram Events, Calendar Object and more in PSWriteHTML](https://evotec.xyz/nested-tabs-diagram-updates-diagram-events-calendar-object-and-more-in-pswritehtml/)
- 🔗 [Emailimo merged into PSWriteHTML, IE support and no dependencies](https://evotec.xyz/emailimo-merged-into-pswritehtml-ie-support-and-no-dependencies/)
- 🔗 [Active Directory DHCP Report to HTML or EMAIL with zero HTML knowledge](https://evotec.xyz/active-directory-dhcp-report-to-html-or-email-with-zero-html-knowledge/)
- 🔗 [Creating Office 365 Migration Diagram with PowerShell](https://evotec.xyz/creating-office-365-migration-diagram-with-powershell/)
- 🔗 [Advanced HTML reporting using PowerShell](https://evotec.xyz/advanced-html-reporting-using-powershell/)

It will give you a start. Then you can go into the Examples folder, run them and see what happens and how it's getting built. 

There are no other docs, as I have no time to create those, and there's very limited support from people in helping with those. Once people get hang of it, they just start using it without thinking to update docs for someone else. 

As for your alignment, it could be fixed - it's padded by default 17px, when changed to 5px it moves it properly

![image](https://user-images.githubusercontent.com/15063294/114756809-6a8ad400-9d5b-11eb-82f9-86dc08b436df.png)

Maybe someday I'll update it.

As for the sizing, there's very rarely need to play with width. As soon as you start adding things and pushing more content it will resize to much smaller object.

**Comment by matteu31400** [comment] 2021-04-14 18:02
Thanks for this return.
Maybe one last question.

I try to test your new advice to align on the left but maybe I don't use it correctly ?

my test code :

```
function Get-ReportProcess {
    Get-Process | ForEach-Object {
        [pscustomobject]@{
            Name = $_.ProcessName
            ID   = $_.id
        }
    }
}

function Get-ReportServices {
    Get-service | ForEach-Object {
        [pscustomobject]@{
            Name = $_.Name
            ID   = $_.status
        }
    }
}


$ReportProcess = Get-ReportProcess
$ReportServices = Get-ReportServices


New-HTML -Name "My title" -FilePath c:\Example04.html {
    New-HTMLTab -Name "Inventory" {
        New-HTMLSection -Name Process {
            New-HTMLTable -DataTable $ReportProcess {
                New-TableHeader -Alignment left -Names 'Name', 'ID'
            }
        }

        New-HTMLSection -Name Services {
            New-HTMLTable -DataTable $ReportServices {
                New-TableHeader -Alignment left -Names 'Name', 'Status'
            }
        }
    }
} -ShowHTML -Online
```

my result 

![2021-04-14_20h01_49](https://user-images.githubusercontent.com/55273549/114757568-4e3b6700-9d5c-11eb-8a18-1f98852e0c54.png)

**Comment by PrzemyslawKlys** [comment] 2021-04-14 18:04
You changed `New-TableHeader -Alignment left -Names 'Name', 'Status'` to Name/Status - There are no Status column in the 2nd table.

**Comment by matteu31400** [comment] 2021-04-14 18:06
Oh right my bad...
I forget to change it in my function... ID need to be replaced by status :)

Sorry about it and thank you very much for your help

**Closed** 2021-04-14 18:07 UTC
Labels: support

**Comment by tomerikko** [comment] 2021-04-14 19:43
@PrzemyslawKlys , that align example is great!
i was messing with the titles a few times now, and didnt got it to work as i wish, but now looking at your example i think its because i use with the New-TableHeader the "-Title" option.

on anyway, i will go now and play with it again, but i suggest to add that example to the list of examples you share with the code.

**Comment by PrzemyslawKlys** [comment] 2021-04-14 20:29
The Title is for adding Title over 1 or more rows

![image](https://user-images.githubusercontent.com/15063294/114774497-8b115900-9d70-11eb-87c8-458f2898ee93.png)

```powershell
New-TableHeader -Alignment left -Names 'Name', 'Id' -Title 'Title'
```
That cmdlet has multiple options to control how things are looking. Anyways I see there's a bug where TItle/Names alignment needs to be fixed. There should be 2 separate alignements.
