### ISSUE TITLE
DATATABLE warning - Cannot reinitialize DataTable

### ISSUE THREAD

**Issue by wpiotrw** [EvotecIT/PSWriteHTML#126] opened 2020-05-27 13:08 UTC
Hello

I am facing the below error while using DASHIMO (PSWRITEHTML)

![obraz](https://user-images.githubusercontent.com/37083541/83022298-9b6ef700-a02b-11ea-9726-85f6a6dfe2ad.png)

Possible resolution as per url on the screenshot: https://datatables.net/manual/tech-notes/3
To be implemented directly in your modules? (FIX?)

PS code used to create dashobard: https://evotec.xyz/getting-azure-health-parsing-html-website-using-psparsehtml/

Error occurs during switching beteen tabs.

Thanks
Piotr

**Comment by PrzemyslawKlys** [comment] 2020-05-27 20:05
I couldn't reproduce your issue but I've seen this error. 

It's most likely relevant to this: https://github.com/EvotecIT/PSWriteHTML/issues/101 which was fixed in this: https://github.com/EvotecIT/PSWriteHTML/pull/105 

Due to the way we work when switching tabs and refreshing tables on tab switching I guess when it refreshes too fast it potentially could do what you see. @opustecnica worked on this but not sure if it can be easily addressed.

**Comment by opustecnica** [comment] 2020-05-28 11:50
All,

I will look at it this weekend.

 @wpiotrw 
Can you add details in order to replicate? (e.g. browser, version, etc.)

THX.

**Comment by wpiotrw** [comment] 2020-07-21 09:25
I checked FF and Chrome - version does not matter.), 
just try to switch between tabs a lot.

**Comment by PrzemyslawKlys** [comment] 2020-08-12 15:29
@opustecnica here's where you can replicate it. Open it up and as quickly as possible try to switch to the 2nd tab. 

[GPOReport2.zip](https://github.com/EvotecIT/PSWriteHTML/files/5063721/GPOReport2.zip)

This can be replicated when there is a large number of tables that are still loading "somewhere" and you try to play with tabs.

**Comment by smasterson** [comment] 2020-10-28 12:11
0.0.118 made a huge impact for me on my monster 89 tab dashboard.
'Don't touch the tabs until the page fully refreshes!' - it was becoming quite an issue for us.
Now I cannot even force the error no matter how fast I click around tabs after a page refresh 👍

**Comment by PrzemyslawKlys** [comment] 2020-10-28 12:23
Glad it works. There's one more thing I need to do because I believe we should be able to initialize Tables only once per tab. This means I would need to track if the table was already initialized at least once and if so doesn't do it again on tab switch. I am not sure what impact will it have so this will need to be tested. This also needs to be added to new tabs, sections, and other things that may impact visibility. 

This is needed because in Testimo where I have 4 tabs, but like 200+ tables on each tab switching between tabs is causing HTML to be really painful - and I mean like 1 minute per tab reload.

To improve performance even further you can use:

```powershell
New-HTML {
    New-HTMLTableOption -DateTimeFormat "yyyy-MM-dd HH:mm:ss" -BoolAsString -DataStore JavaScript
}
```
DataStore JavaScript can process large datasets really well, and with those options DateTimeFormat / BoolAsString you can adjust how data is displayed in the table. Since data is stored differently most of the things are no longer treated as text and I had to build my own custom ConvertTo-JsonLiteral to provide this feature. 

So before you deploy make sure to check this out as some output may change... and not work as you expect it to depending on which features you use in your tables.

**Comment by PrzemyslawKlys** [comment] 2020-12-09 19:05
I've tried to further enhance this by tracking use of initialized tables. Unfortunetly I can't detect if Table is hidden or shown so it's hard to know if initialization happened at the right moment. I'm going to close this error, as the error doesn't show up anymore, but performance of this solution should be discussed in future if it will be a problem.

**Closed by PrzemyslawKlys** 2020-12-09 19:05 UTC
Labels: bug, help wanted
